### PR TITLE
27 create form page answer options

### PR DESCRIPTION
**Pull request by Quenayalui**
ready add-participants & answer-options pages

### CODE REVIEW

**Review by verascheunert — COMMENTED** [review]
Looks good so far, could you please resolve the conflicts you are having with main :) Thanks a bunch!

**Comment by Quenayalui** [comment]
@verascheunert yes will do. its so weird, i already solved these exact conflicts when made the pull request, you know why they would appear again?

**Comment by verascheunert** [comment]
Mh, I don't know why exactly they would come again, maybe something went wrong in the pushing process or someone touched the files?

**Comment by Quenayalui** [comment]
ok i think its ready @verascheunert

**Pull request merged**
